name: 'AI PR Reviewer'
description: 'Automated pull request reviews using OpenAI GPT-4'
author: 'Bikram Sutar'

inputs:
  github-token:
    description: 'GitHub token for PR access'
    required: true
    default: ${{ github.token }}
  openai-api-key:
    description: 'OpenAI API key'
    required: true
  model:
    description: 'OpenAI model to use'
    required: false
    default: 'gpt-3.5-turbo'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: poetry install --no-interaction --no-root

    - name: Run PR Review
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        OPENAI_MODEL: ${{ inputs.model }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: poetry run python src/review_pr.py